"""
Water Meter Reading Validation & Average Workbook Update Script

Overview:
---------
This script parses monthly water meter consumption reports generated by WaterOn
(e.g., 'Consumption Report July-2026-ver1-8-10-26.xlsx'), maps total consumption
readings flat-by-flat (F1..F16, G1..G16, S1..S16, T1..T16), updates the target month's
column in the average water usage workbook ('db/wateron/avg-water-usage.xlsx'),
calculates the variance percentage from the overall flat average in the last column (Column M),
and highlights any flats with a variance higher than the configurable threshold (default: 50%) in red.

Pre-conditions:
---------------
1. WaterOn Report Filename Convention:
   The input WaterOn consumption report filename MUST follow the pattern
   'Consumption Report <Month>-<YYYY>*.xlsx' (e.g. 'Consumption Report July-2026-ver1-8-10-26.xlsx',
   'Consumption Report Jul-2026.xlsx', or 'Consumption Report 07-2026.xlsx').

2. Average Water Usage File Existence:
   The target average workbook MUST exist at 'db/wateron/avg-water-usage.xlsx' relative to the repository
   root (or passed explicitly as the second CLI argument).

3. Average Workbook Column & Header Layout:
   - Row 1 MUST contain column headers: Column A ('flat#'), Column L ('average water usage (L)'),
     and Column M ('Variance %').
   - Row 1 MUST contain a column header matching the target month and year (e.g. July 2026 in Column F).

4. WaterOn Report Structure:
   The first row of the WaterOn consumption Excel report MUST contain 'Apartment' and 'Total' columns.

5. File Lock / Write Access:
   The target average workbook Excel file ('avg-water-usage.xlsx') MUST NOT be open in Microsoft Excel
   or locked by another application.

Key Configurations & Parameters:
--------------------------------
- PROJECT_ROOT: Resolved dynamically relative to script location.
- DEFAULT_AVG_WATER_USAGE_FILE: Always points to 'db/wateron/avg-water-usage.xlsx' relative to project root
  (e.g. C:\\github\\manapristine\\db\\wateron\\avg-water-usage.xlsx), independent of working directory.
- DEFAULT_VARIANCE_THRESHOLD_PCT: Default variance threshold percentage (50.0%).
  Can be overridden via the `--threshold` / `-t` CLI option or function argument.

Key Assumptions & Conventions:
------------------------------
1. Average Workbook Layout:
   - Row 1 contains column headers.
   - Column A (1): Flat Identifier ('flat#')
   - Column B (2): Flat Owner Name ('flat owner')
   - Columns C to K (3..11): Monthly consumption columns starting April to December.
   - Column L (12): Average Water Usage ('average water usage (L)'), containing `=SUM(C{r}:K{r})/COUNT(C{r}:K{r})`.
   - Column M (13): Designated Last Column for 'Variance %'.

2. WaterOn Consumption Report Layout:
   - The WaterOn Excel report header row contains columns named 'Apartment' and 'Total'.
   - Residential flat totals are on rows where 'Apartment' is populated (e.g. F1, G16).
   - Sub-meter rows (where 'Apartment' is empty/NaN) and non-flat summary rows ('TOTAL', 'CH', 'GYM', 'BSMT')
     are excluded from flat variance processing.

3. Flat Normalization & Mapping Scope:
   - Society flats cover 64 residential units across F, G, S, and T blocks (F1-F16, G1-G16, S1-S16, T1-T16).
   - Flat IDs are normalized to uppercase without spaces or leading zeros (e.g., 'f 01' -> 'F1').

4. Configurable High Variance Threshold (> +Threshold%):
   - "Variance higher than threshold" is defined as positive variance `variance_pct > +(Threshold / 100)`
     (e.g., +50% increase over average), flagging potential water leaks, meter malfunctions, or surge consumption.

5. Formula & Error Handling:
   - Injects Excel `=IFERROR(({month_col}{row}-L{row})/L{row}, 0)` to gracefully prevent `#DIV/0!` errors.

CLI Usage:
----------
1. Basic Usage (uses project root avg-water-usage.xlsx path and 50% threshold):
   python report_builder/validate_water_meter_reading.py "db/wateron/26-27/Consumption Report July-2026-ver1-8-10-26.xlsx"

2. Custom Variance Threshold (e.g. 30% threshold):
   python report_builder/validate_water_meter_reading.py "db/wateron/26-27/Consumption Report July-2026-ver1-8-10-26.xlsx" --threshold 30

3. Explicit Paths and Threshold:
   python report_builder/validate_water_meter_reading.py "path/to/Consumption Report July-2026.xlsx" "path/to/avg-water-usage.xlsx" -t 40

4. Help Menu:
   python report_builder/validate_water_meter_reading.py --help

Exit Codes:
-----------
  0: Success (workbook updated successfully)
  1: Failure (missing file, invalid format, permission denied, missing column)
"""

import os
import re
import sys
import argparse
from datetime import datetime, date
from pathlib import Path
import openpyxl
from openpyxl.styles import PatternFill, Font
from openpyxl.formatting.rule import CellIsRule
from openpyxl.utils import get_column_letter

# Project Root and Default File Paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_AVG_WATER_USAGE_FILE = PROJECT_ROOT / "db" / "wateron" / "avg-water-usage.xlsx"

# Default Configuration Constants
DEFAULT_VARIANCE_THRESHOLD_PCT = 50.0  # Percentage threshold for highlighting high water usage (50.0%)

def normalize_flat(flat):
    """Normalize flat identifiers to consistent uppercase standard (e.g. F1, G16, CH)."""
    if flat is None:
        return ""
    flat = str(flat).strip().upper()
    mapping = {
        'C H': 'CH',
        'C GYM': 'GYM',
        'CBR': 'BSMT'
    }
    flat = mapping.get(flat, flat.replace(" ", ""))
    # Normalize zero-padded flat numbers like F01 -> F1, G09 -> G9
    flat = re.sub(r'^([A-Z])0+(\d+)$', r'\1\2', flat)
    return flat

def parse_wateron_filename(filepath):
    """Extract month (1-12) and year (YYYY) from WaterOn report filename."""
    filename = os.path.basename(filepath)
    match = re.search(r'Consumption Report (?P<month>[a-zA-Z0-9]+)[-_ ](?P<year>\d{4})', filename, re.IGNORECASE)
    if not match:
        raise ValueError(f"Could not parse month and year from filename: '{filename}'")
    
    month_str = match.group('month').lower()
    year = int(match.group('year'))
    
    if month_str.isdigit():
        month = int(month_str)
        if not (1 <= month <= 12):
            raise ValueError(f"Invalid month number in filename: '{month_str}'")
    else:
        month_map = {
            'january': 1, 'february': 2, 'march': 3, 'april': 4, 'may': 5, 'june': 6,
            'july': 7, 'august': 8, 'september': 9, 'october': 10, 'november': 11, 'december': 12,
            'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6, 'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
        }
        month = month_map.get(month_str)
        if not month:
            raise ValueError(f"Unknown month string in filename: '{month_str}'")
    
    return month, year

def load_wateron_data(filepath):
    """Load water consumption data from WaterOn report."""
    try:
        wb = openpyxl.load_workbook(filepath, data_only=True, read_only=True)
        ws = wb.active
        
        data = {}
        header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True))
        headers = [str(h).strip() if h else "" for h in header_row]
        
        try:
            apt_idx = headers.index('Apartment')
            total_idx = headers.index('Total')
        except ValueError:
            print("Error: Could not find 'Apartment' or 'Total' columns in WaterOn report.")
            return {}

        for row in ws.iter_rows(min_row=2, values_only=True):
            apt = row[apt_idx]
            if apt:
                flat_id = normalize_flat(apt)
                if flat_id in ["TOTAL", "CH", "GYM", "BSMT"]:
                    continue
                total = row[total_idx]
                if isinstance(total, (int, float)):
                    data[flat_id] = float(total)
        
        return data
    finally:
        if 'wb' in locals():
            wb.close()

def find_month_column(ws, month, year):
    """Find column index (1-based) for given month and year in row 1 headers."""
    header_cells = list(ws.iter_rows(min_row=1, max_row=1))[0]
    month_names_short = ['', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
    month_names_full = ['', 'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']

    for idx, cell in enumerate(header_cells, start=1):
        val = cell.value
        if val is None:
            continue
        if isinstance(val, (datetime, date)):
            if val.month == month and val.year == year:
                return idx
        elif isinstance(val, str):
            val_lower = val.lower()
            if (month_names_short[month] in val_lower or month_names_full[month] in val_lower or f"-{month:02d}-" in val_lower or f"/{month}/" in val_lower) and str(year) in val_lower:
                return idx
    return None

def validate_and_update_water_meter_reading(consumption_file, avg_file=None, variance_threshold_pct=DEFAULT_VARIANCE_THRESHOLD_PCT):
    """
    Update average water usage file with monthly readings and highlight high variance.

    :param consumption_file: Path to WaterOn monthly consumption report Excel file.
    :param avg_file: Path to average water usage Excel workbook (defaults to PROJECT_ROOT/db/wateron/avg-water-usage.xlsx).
    :param variance_threshold_pct: Variance percentage threshold for highlighting (default: 50.0%).
    :return: bool success
    """
    consumption_path = Path(consumption_file)
    if not consumption_path.exists() and not consumption_path.is_absolute():
        alt_consumption = PROJECT_ROOT / consumption_file
        if alt_consumption.exists():
            consumption_path = alt_consumption

    if avg_file is None:
        avg_path = DEFAULT_AVG_WATER_USAGE_FILE
    else:
        avg_path = Path(avg_file)
        if not avg_path.exists() and not avg_path.is_absolute():
            alt_avg = PROJECT_ROOT / avg_file
            if alt_avg.exists():
                avg_path = alt_avg

    if not consumption_path.exists():
        print(f"Error: Consumption report not found: {consumption_path}")
        return False
    if not avg_path.exists():
        print(f"Error: Average water usage file not found: {avg_path}")
        return False

    month, year = parse_wateron_filename(consumption_path.name)
    month_name = datetime(year, month, 1).strftime("%B %Y")
    threshold_ratio = variance_threshold_pct / 100.0

    print(f"Processing Water Meter Readings for: {month_name}")
    print(f"Variance Highlighting Threshold: > {variance_threshold_pct}% (+{threshold_ratio})")

    water_data = load_wateron_data(consumption_path)
    if not water_data:
        print("Error: No valid consumption data found in report.")
        return False

    try:
        wb = openpyxl.load_workbook(avg_path)
    except PermissionError:
        print(f"Error: Permission denied. Please ensure '{avg_path.name}' is closed in Excel.")
        return False

    ws = wb.active
    month_col_idx = find_month_column(ws, month, year)
    if not month_col_idx:
        print(f"Error: Could not find column for {month_name} in '{avg_path.name}'.")
        wb.close()
        return False

    month_col_letter = get_column_letter(month_col_idx)
    var_col_idx = 13  # Last column M
    var_col_letter = get_column_letter(var_col_idx)

    # Set column header for variance column
    ws.cell(row=1, column=var_col_idx, value="Variance %")

    # Styling for > threshold variance
    red_fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
    red_font = Font(color="9C0006", bold=True)

    updates_count = 0
    flagged_flats = []

    for row_idx in range(2, ws.max_row + 1):
        flat_cell = ws.cell(row=row_idx, column=1)
        flat_id = normalize_flat(flat_cell.value)
        if not flat_id:
            continue

        if flat_id in water_data:
            current_reading = water_data[flat_id]
            # Write total reading in the month's column
            ws.cell(row=row_idx, column=month_col_idx, value=current_reading)
            updates_count += 1

            # Variance formula comparing current month against average column (L)
            var_cell = ws.cell(row=row_idx, column=var_col_idx)
            var_cell.value = f"=IFERROR(({month_col_letter}{row_idx}-L{row_idx})/L{row_idx}, 0)"
            var_cell.number_format = "0.0%"

            # Calculate numeric average & variance in Python for highlighting determination
            month_vals = []
            for col in range(3, 12):  # Columns C (3) to K (11)
                val = ws.cell(row=row_idx, column=col).value
                if isinstance(val, (int, float)):
                    month_vals.append(val)
            
            if month_vals:
                avg_usage = sum(month_vals) / len(month_vals)
                variance_pct = (current_reading - avg_usage) / avg_usage if avg_usage > 0 else 0.0
            else:
                variance_pct = 0.0

            # Highlight if variance % is higher than threshold
            if variance_pct > threshold_ratio:
                var_cell.fill = red_fill
                var_cell.font = red_font
                flagged_flats.append((flat_id, current_reading, avg_usage, variance_pct))

    # Add dynamic Excel Conditional Formatting rule for column M
    rule = CellIsRule(operator='greaterThan', formula=[str(threshold_ratio)], stopIfTrue=True, fill=red_fill, font=red_font)
    ws.conditional_formatting.add(f"{var_col_letter}2:{var_col_letter}{ws.max_row}", rule)

    try:
        wb.save(avg_path)
        print(f"\nSuccessfully updated {updates_count} flats in '{avg_path.name}' for {month_name}.")
        print(f"Variance formula added to column {var_col_letter}.")
        
        if flagged_flats:
            print(f"\n[ALERT] {len(flagged_flats)} flat(s) exceeded {variance_threshold_pct}% variance from average (HIGHLIGHTED RED):")
            print(f"{'Flat':<8} | {'Current Reading (L)':<20} | {'Average Usage (L)':<20} | {'Variance %':<12}")
            print("-" * 68)
            for flat_id, curr, avg, var in flagged_flats:
                print(f"{flat_id:<8} | {curr:<20.1f} | {avg:<20.1f} | {var*100:>+10.1f}%")
        else:
            print(f"\nNo flats exceeded +{variance_threshold_pct}% variance.")
        return True
    except PermissionError:
        print(f"Error: Could not save '{avg_path.name}'. File may be open in Excel.")
        return False
    finally:
        wb.close()

def main():
    parser = argparse.ArgumentParser(description="Validate monthly water meter readings against average usage.")
    parser.add_argument("consumption_file", help="Path to monthly WaterOn consumption report Excel file.")
    parser.add_argument(
        "avg_file",
        nargs="?",
        default=str(DEFAULT_AVG_WATER_USAGE_FILE),
        help=f"Path to average water usage Excel workbook (default: {DEFAULT_AVG_WATER_USAGE_FILE})."
    )
    parser.add_argument(
        "--threshold", "-t",
        type=float,
        default=DEFAULT_VARIANCE_THRESHOLD_PCT,
        help=f"Variance percentage threshold for highlighting high water usage (default: {DEFAULT_VARIANCE_THRESHOLD_PCT}%)."
    )
    args = parser.parse_args()

    success = validate_and_update_water_meter_reading(
        args.consumption_file,
        args.avg_file,
        variance_threshold_pct=args.threshold
    )
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
